=== Emir-Oguz/Density-Measurement/17016011_Emir_Oğuz/17016011_Emir_Oğuz/C/STD_CNF/R/STD_RES/_s49IBG4/service.dtd
<!ELEMENT Sequences (Sequence*)>
<!ELEMENT Sequence (Name, ServiceRequest+)>
<!ELEMENT ServiceRequest (Name, RequestCode, Parameters?)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT RequestCode (#PCDATA)>
<!ELEMENT Parameters (Param+)>
<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param Datatype 
   (unsigned8 |
    unsigned16 | 
    unsigned32 | 
    octetString) #REQUIRED>
<!ATTLIST Param Description CDATA #REQUIRED>

=== Emir-Oguz/Density-Measurement/17016011_Emir_Oğuz/17016011_Emir_Oğuz/C/STD_CNF/R/STD_RES/_s49IBG4/ControllerSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequences SYSTEM "Service.dtd">
<Sequences>
	<Sequence>
		<Name>Bus_Timing</Name>
		<ServiceRequest>
			<Name>Set_Value_Request</Name>
			<RequestCode>0x0750</RequestCode>
			<Parameters>
				<Param Description="Value Count" Datatype="unsigned16">1</Param>
				<Param Description="Variable ID" Datatype="unsigned16">0x2200</Param>
				<Param Description="Bus Operation Mode (ASYMSI)" Datatype="unsigned32">0x06000000</Param>
			</Parameters>
		</ServiceRequest>
	</Sequence>
</Sequences>
